import type { KnowledgeSource } from "@/lib/research/types";

const NOW = "2026-06-14T10:00:00.000Z";

export const MOCK_KNOWLEDGE_SOURCES: KnowledgeSource[] = [
  {
    id: "src-tournaments",
    name: "Tournament rounds",
    source_type: "tournaments",
    description: "Saved tournament rounds, phases, and completion metadata.",
    permission_level: "public",
    freshness_policy: "realtime",
    reliability_score: 0.95,
    indexing_status: "ready",
    vector_collection_name: "arena_tournaments_v1",
    record_count: 12,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-challenges",
    name: "Challenge catalog",
    source_type: "challenges",
    description: "Generated and selected challenge briefs per round.",
    permission_level: "public",
    freshness_policy: "hourly",
    reliability_score: 0.9,
    indexing_status: "ready",
    vector_collection_name: "arena_challenges_v1",
    record_count: 36,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-agent-runs",
    name: "Agent runs",
    source_type: "agent_runs",
    description: "Competitor agent outputs, tokens, cost, and latency per run.",
    permission_level: "public",
    freshness_policy: "realtime",
    reliability_score: 0.92,
    indexing_status: "ready",
    vector_collection_name: "arena_agent_runs_v1",
    record_count: 64,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-evaluations",
    name: "Judge evaluations",
    source_type: "evaluations",
    description: "Quality and efficiency scores from judge agents.",
    permission_level: "public",
    freshness_policy: "realtime",
    reliability_score: 0.9,
    indexing_status: "ready",
    vector_collection_name: "arena_evaluations_v1",
    record_count: 64,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-leaderboard",
    name: "Leaderboard history",
    source_type: "leaderboard_entries",
    description: "Rankings, win rates, and score trends across rounds.",
    permission_level: "public",
    freshness_policy: "hourly",
    reliability_score: 0.88,
    indexing_status: "ready",
    vector_collection_name: "arena_leaderboard_v1",
    record_count: 48,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-marketplace",
    name: "Marketplace components",
    source_type: "marketplace_components",
    description: "Tournament-tested workflow components and Arena Scores.",
    permission_level: "public",
    freshness_policy: "daily",
    reliability_score: 0.82,
    indexing_status: "ready",
    vector_collection_name: "arena_marketplace_v1",
    record_count: 14,
    last_indexed_at: "2026-06-13T18:00:00.000Z",
    freshness_status: "aging",
    enabled: true,
  },
  {
    id: "src-memory",
    name: "Memory articles",
    source_type: "memory_articles",
    description: "Compiled tournament lessons, failures, and routing insights.",
    permission_level: "public",
    freshness_policy: "daily",
    reliability_score: 0.85,
    indexing_status: "ready",
    vector_collection_name: "arena_memory_v1",
    record_count: 18,
    last_indexed_at: "2026-06-13T22:00:00.000Z",
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-tool-logs",
    name: "Tool Arena logs",
    source_type: "tool_call_logs",
    description: "Tool call audit logs, permission denials, and verification notes.",
    permission_level: "authenticated",
    freshness_policy: "realtime",
    reliability_score: 0.78,
    indexing_status: "ready",
    vector_collection_name: "arena_tool_logs_v1",
    record_count: 42,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-forecast",
    name: "Forecast runs",
    source_type: "forecast_runs",
    description: "Token, cost, and provider risk forecasts from intelligence layer.",
    permission_level: "public",
    freshness_policy: "hourly",
    reliability_score: 0.7,
    indexing_status: "ready",
    vector_collection_name: "arena_forecast_v1",
    record_count: 6,
    last_indexed_at: NOW,
    freshness_status: "fresh",
    enabled: true,
  },
  {
    id: "src-uploads",
    name: "Uploaded documents",
    source_type: "uploaded_documents",
    description: "User-uploaded PDFs and docs (future).",
    permission_level: "enterprise",
    freshness_policy: "manual",
    reliability_score: 0.6,
    indexing_status: "disabled",
    vector_collection_name: null,
    record_count: 0,
    last_indexed_at: null,
    freshness_status: "unknown",
    enabled: false,
  },
  {
    id: "src-web",
    name: "External web",
    source_type: "external_web",
    description: "Optional web research corpus (future).",
    permission_level: "admin",
    freshness_policy: "manual",
    reliability_score: 0.5,
    indexing_status: "disabled",
    vector_collection_name: null,
    record_count: 0,
    last_indexed_at: null,
    freshness_status: "unknown",
    enabled: false,
  },
];

export function getKnowledgeSource(id: string): KnowledgeSource | undefined {
  return MOCK_KNOWLEDGE_SOURCES.find((s) => s.id === id);
}
