import type { TradingChallenge } from "@/lib/trading-arena/types";

const NOW = "2026-06-14T12:00:00.000Z";

export const MOCK_TRADING_CHALLENGES: TradingChallenge[] = [
  {
    id: "chal-btc-mr",
    tournament_id: "trading-tournament-1",
    round: 1,
    title: "BTC mean reversion in high-volatility regimes",
    brief:
      "Design a BTCUSD mean-reversion strategy that activates only when 30-day realized volatility exceeds the 1-year median.",
    asset_class: "crypto",
    universe: ["BTCUSD"],
    benchmark: "BTCUSD",
    start_date: "2021-01-01",
    end_date: "2024-12-31",
    resolution: "hour",
    constraints: { max_drawdown_pct: 25, max_leverage: 1, max_turnover_annual: 12 },
    status: "open",
    created_at: NOW,
  },
  {
    id: "chal-spy-momentum",
    tournament_id: "trading-tournament-1",
    round: 1,
    title: "SPY momentum with drawdown control",
    brief: "Create a SPY trend-following strategy with explicit max drawdown circuit breaker at 15%.",
    asset_class: "equity",
    universe: ["SPY"],
    benchmark: "SPY",
    start_date: "2018-01-01",
    end_date: "2024-12-31",
    resolution: "daily",
    constraints: { max_drawdown_pct: 15, max_leverage: 1, max_turnover_annual: 6 },
    status: "open",
    created_at: NOW,
  },
  {
    id: "chal-sector-rotation",
    tournament_id: null,
    round: null,
    title: "Sector rotation with monthly rebalance",
    brief: "Rotate among XLK, XLF, XLE based on 3-month relative momentum; rebalance monthly.",
    asset_class: "equity",
    universe: ["XLK", "XLF", "XLE"],
    benchmark: "SPY",
    start_date: "2015-01-01",
    end_date: "2024-12-31",
    resolution: "daily",
    constraints: { max_drawdown_pct: 20, max_leverage: 1, max_turnover_annual: 24 },
    status: "open",
    created_at: NOW,
  },
  {
    id: "chal-sol-hedge",
    tournament_id: null,
    round: null,
    title: "SOL long exposure hedge strategy",
    brief: "Maintain SOL long with options-style hedge rules simulated via vol-scaled cash buffer (mock).",
    asset_class: "crypto",
    universe: ["SOLUSD"],
    benchmark: "SOLUSD",
    start_date: "2022-01-01",
    end_date: "2024-12-31",
    resolution: "hour",
    constraints: { max_drawdown_pct: 30, max_leverage: 1.5, max_turnover_annual: 8 },
    status: "open",
    created_at: NOW,
  },
  {
    id: "chal-regime-filter",
    tournament_id: null,
    round: null,
    title: "Market regime filter (MA + volatility)",
    brief: "Trade SPY only when price > 200d MA and VIX proxy vol below 75th percentile.",
    asset_class: "equity",
    universe: ["SPY"],
    benchmark: "SPY",
    start_date: "2010-01-01",
    end_date: "2024-12-31",
    resolution: "daily",
    constraints: { max_drawdown_pct: 18, max_leverage: 1, max_turnover_annual: 4 },
    status: "open",
    created_at: NOW,
  },
];

export function getTradingChallenge(id: string): TradingChallenge | undefined {
  return MOCK_TRADING_CHALLENGES.find((c) => c.id === id);
}
