import type { AgentPersona, AgentPersonaId } from "@/lib/agents/types";

/** The 10 AI Agent competitors that seed the arena before human users arrive. */
export const AGENT_PERSONAS: AgentPersona[] = [
  {
    id: "frugal",
    name: "Frugal",
    archetype: "Low-cost agent",
    strategy: "Single-pass summary on the cheapest viable model with a terse prompt.",
    modelPref: "claude-3-5-haiku",
    tokenBudget: 3000,
    strengths: "Cheapest and fastest; great quality-per-dollar baseline.",
    weaknesses: "Misses nuance; thin risk analysis.",
    promptStyle: "Minimal instructions, no examples.",
    costBehavior: "very-low",
    steps: [
      "Single call: summarize the report into the 5 required sections",
      "Trim output to fit the token budget",
    ],
  },
  {
    id: "laureate",
    name: "Laureate",
    archetype: "High-quality agent",
    strategy: "Draft → self-critique against the rubric → finalize on a top model.",
    modelPref: "claude-opus-4-8",
    tokenBudget: 25000,
    strengths: "Highest accuracy and structure.",
    weaknesses: "Expensive and slow.",
    promptStyle: "Rich, rubric-driven prompts.",
    costBehavior: "high",
    steps: [
      "Generate a full draft summary",
      "Self-critique the draft against every rubric dimension",
      "Rewrite into a polished, board-ready summary",
    ],
  },
  {
    id: "sprinter",
    name: "Sprinter",
    archetype: "Fast agent",
    strategy: "One streaming call, low max-tokens, latency-optimized, format-locked.",
    modelPref: "claude-sonnet-4-6",
    tokenBudget: 5000,
    strengths: "Lowest latency.",
    weaknesses: "Sacrifices depth for speed.",
    promptStyle: "Compact, output-format-locked.",
    costBehavior: "low",
    steps: [
      "Single streaming call with a strict output template",
      "Return immediately once all sections are filled",
    ],
  },
  {
    id: "hivemind",
    name: "Hivemind",
    archetype: "Multi-agent reasoning agent",
    strategy: "A planner splits the work across specialist sub-agents, then an aggregator merges.",
    modelPref: "claude-sonnet-4-6 ×N",
    tokenBudget: 30000,
    strengths: "Robust, balanced coverage of every dimension.",
    weaknesses: "Token-heavy; orchestration risk.",
    promptStyle: "Role-segmented system prompts.",
    costBehavior: "high",
    steps: [
      "Planner decomposes the report into facts / risks / recommendations",
      "Specialist sub-agents handle each segment in parallel",
      "Aggregator merges the parts into one summary",
    ],
  },
  {
    id: "scholar",
    name: "Scholar",
    archetype: "Retrieval-augmented agent",
    strategy: "Chunk → embed → retrieve the most relevant passages → grounded synthesis with citations.",
    modelPref: "claude-sonnet-4-6 + embeddings",
    tokenBudget: 12000,
    strengths: "Lowest hallucination; grounded and defensible.",
    weaknesses: "A retrieval miss hurts completeness.",
    promptStyle: "Citation-required prompts.",
    costBehavior: "medium",
    steps: [
      "Chunk and embed the report",
      "Retrieve passages relevant to each required section",
      "Synthesize a grounded summary citing the source passages",
    ],
  },
  {
    id: "spartan",
    name: "Spartan",
    archetype: "Minimal prompt agent",
    strategy: "A single one-line instruction with zero scaffolding — the token-efficiency baseline.",
    modelPref: "claude-sonnet-4-6",
    tokenBudget: 2000,
    strengths: "Most token-efficient.",
    weaknesses: "Inconsistent formatting.",
    promptStyle: "Bare instruction.",
    costBehavior: "very-low",
    steps: [
      "Single call: \"Summarize this report for an executive.\"",
    ],
  },
  {
    id: "architect",
    name: "Architect",
    archetype: "Chain-of-thought planning agent",
    strategy: "Build an explicit plan, then execute the plan into a fixed output template.",
    modelPref: "claude-opus-4-8",
    tokenBudget: 15000,
    strengths: "Excellent structure and completeness.",
    weaknesses: "Verbose; mid-to-high cost.",
    promptStyle: "\"Think step by step, then produce the output.\"",
    costBehavior: "medium-high",
    steps: [
      "Plan: outline what each section must contain",
      "Execute the plan section by section",
      "Fill the executive template",
    ],
  },
  {
    id: "redliner",
    name: "Redliner",
    archetype: "Critic / refiner agent",
    strategy: "Generate → self-critique loop ×2 → refine. Catches its own errors.",
    modelPref: "claude-sonnet-4-6",
    tokenBudget: 18000,
    strengths: "High accuracy; catches omissions.",
    weaknesses: "Diminishing returns on cost.",
    promptStyle: "Adversarial self-review prompts.",
    costBehavior: "medium-high",
    steps: [
      "Generate an initial summary",
      "Critique: find 3 errors or omissions",
      "Refine, then repeat the critique once more",
    ],
  },
  {
    id: "sentinel",
    name: "Sentinel",
    archetype: "Risk-focused agent",
    strategy: "Extract content, run a dedicated risk pass, then assemble the summary.",
    modelPref: "claude-sonnet-4-6",
    tokenBudget: 10000,
    strengths: "Best risk identification.",
    weaknesses: "Over-indexes on risk; weaker recommendations.",
    promptStyle: "Risk-taxonomy prompts.",
    costBehavior: "medium",
    steps: [
      "Extract key facts from the report",
      "Dedicated pass: enumerate and rank strategic risks",
      "Assemble the summary around the risk findings",
    ],
  },
  {
    id: "atlas",
    name: "Atlas",
    archetype: "Enterprise-style agent",
    strategy: "Compliance-grade output with citations, confidence levels, and an audit trail.",
    modelPref: "claude-opus-4-8",
    tokenBudget: 22000,
    strengths: "Decision-ready and defensible; best recommendations and format.",
    weaknesses: "Costly; formal tone.",
    promptStyle: "Governance / format-strict prompts.",
    costBehavior: "high",
    steps: [
      "Extract facts with confidence levels and citations",
      "Draft a governance-grade summary",
      "Attach an audit note and format-compliance check",
    ],
  },
];

export function getAgentById(id: AgentPersonaId): AgentPersona | undefined {
  return AGENT_PERSONAS.find((a) => a.id === id);
}
