import type { ToolAction, ToolPlugin } from "@/lib/tool-arena/types";

const NOW = "2026-06-14T12:00:00.000Z";

export const MOCK_TOOL_ACTIONS: ToolAction[] = [
  {
    id: "github-list_issues",
    plugin_id: "github",
    name: "list_issues",
    label: "List issues",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "List open issues for a repository.",
  },
  {
    id: "github-get_pr",
    plugin_id: "github",
    name: "get_pr",
    label: "Get pull request",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Fetch PR metadata and diff summary.",
  },
  {
    id: "github-create_issue",
    plugin_id: "github",
    name: "create_issue",
    label: "Create issue",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Create a GitHub issue from structured fields.",
  },
  {
    id: "discord-get_channel",
    plugin_id: "discord",
    name: "get_channel",
    label: "Get channel",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Read channel metadata.",
  },
  {
    id: "discord-post_message",
    plugin_id: "discord",
    name: "post_message",
    label: "Post message",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Post a summary message to a Discord channel.",
  },
  {
    id: "notion-get_page",
    plugin_id: "notion",
    name: "get_page",
    label: "Get page",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Read Notion page blocks.",
  },
  {
    id: "notion-create_page",
    plugin_id: "notion",
    name: "create_page",
    label: "Create page",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Create action items page from extracted tasks.",
  },
  {
    id: "jira-get_issue",
    plugin_id: "jira",
    name: "get_issue",
    label: "Get issue",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Fetch Jira issue details.",
  },
  {
    id: "jira-create_issue",
    plugin_id: "jira",
    name: "create_issue",
    label: "Create issue",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Create a Jira ticket.",
  },
  {
    id: "figma-get_file",
    plugin_id: "figma",
    name: "get_file",
    label: "Get file",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Read Figma file structure.",
  },
  {
    id: "figma-add_comment",
    plugin_id: "figma",
    name: "add_comment",
    label: "Add QA comment",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Add design QA comment on a frame.",
  },
  {
    id: "supabase-select_rows",
    plugin_id: "supabase",
    name: "select_rows",
    label: "Select rows",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Read rows from a Supabase table.",
  },
  {
    id: "supabase-insert_row",
    plugin_id: "supabase",
    name: "insert_row",
    label: "Insert row",
    kind: "write",
    risk_level: "medium",
    destructive: false,
    description: "Insert benchmark result row.",
  },
  {
    id: "browser-fetch_api",
    plugin_id: "browser",
    name: "fetch_api",
    label: "Fetch internal API",
    kind: "read",
    risk_level: "low",
    destructive: false,
    description: "Call web app internal API via browser session (OpenTabs-style).",
  },
  {
    id: "browser-post_api",
    plugin_id: "browser",
    name: "post_api",
    label: "POST internal API",
    kind: "write",
    risk_level: "high",
    destructive: false,
    description: "POST to web app internal API via authenticated session.",
  },
];

function plugin(
  partial: Omit<ToolPlugin, "available_actions" | "read_actions" | "write_actions">,
): ToolPlugin {
  const actions = MOCK_TOOL_ACTIONS.filter((a) => a.plugin_id === partial.id);
  return {
    ...partial,
    available_actions: actions.map((a) => a.name),
    read_actions: actions.filter((a) => a.kind === "read").map((a) => a.name),
    write_actions: actions.filter((a) => a.kind === "write").map((a) => a.name),
  };
}

export const MOCK_TOOL_PLUGINS: ToolPlugin[] = [
  plugin({
    id: "github",
    name: "GitHub",
    provider: "github",
    category: "devtools",
    description: "Issues, PRs, and repo workflows via API or browser session.",
    permission_level: "off",
    risk_level: "medium",
    auth_method: "oauth",
    enabled: false,
    last_used_at: NOW,
    audit_count: 42,
  }),
  plugin({
    id: "discord",
    name: "Discord",
    provider: "discord",
    category: "communication",
    description: "Post tournament summaries and alerts to Discord channels.",
    permission_level: "off",
    risk_level: "medium",
    auth_method: "api_key",
    enabled: false,
    last_used_at: null,
    audit_count: 18,
  }),
  plugin({
    id: "notion",
    name: "Notion",
    provider: "notion",
    category: "docs",
    description: "Read meeting notes and write action item pages.",
    permission_level: "ask",
    risk_level: "medium",
    auth_method: "oauth",
    enabled: true,
    last_used_at: NOW,
    audit_count: 31,
  }),
  plugin({
    id: "jira",
    name: "Jira",
    provider: "jira",
    category: "project_mgmt",
    description: "Sprint planning and issue triage workflows.",
    permission_level: "off",
    risk_level: "medium",
    auth_method: "api_key",
    enabled: false,
    last_used_at: null,
    audit_count: 12,
  }),
  plugin({
    id: "figma",
    name: "Figma",
    provider: "figma",
    category: "design",
    description: "Design QA comments and file review via API.",
    permission_level: "auto_read",
    risk_level: "low",
    auth_method: "oauth",
    enabled: true,
    last_used_at: NOW,
    audit_count: 9,
  }),
  plugin({
    id: "supabase",
    name: "Supabase",
    provider: "supabase",
    category: "database",
    description: "Log benchmark results and read tournament data.",
    permission_level: "auto_safe",
    risk_level: "low",
    auth_method: "api_key",
    enabled: true,
    last_used_at: NOW,
    audit_count: 56,
  }),
  plugin({
    id: "browser",
    name: "Browser API",
    provider: "browser",
    category: "browser",
    description: "OpenTabs-inspired internal API calls through authenticated browser session.",
    permission_level: "ask",
    risk_level: "high",
    auth_method: "browser_session",
    enabled: true,
    last_used_at: NOW,
    audit_count: 24,
  }),
];

export function getToolAction(pluginId: string, actionName: string): ToolAction | undefined {
  return MOCK_TOOL_ACTIONS.find((a) => a.plugin_id === pluginId && a.name === actionName);
}

export function getToolPlugin(id: string): ToolPlugin | undefined {
  return MOCK_TOOL_PLUGINS.find((p) => p.id === id);
}

export function getActionsForPlugin(pluginId: string): ToolAction[] {
  return MOCK_TOOL_ACTIONS.filter((a) => a.plugin_id === pluginId);
}
